Repository haniehst/OpenTracksW25_Group5, pull requests merged in 2025-03, with the labels that each got.

#27 Refactor: Eliminate code duplication in sensor stats tests
  src/androidTest/java/de/dennisguse/opentracks/data/CustomContentProviderUtilsTest.java
Labels: Technical Debt, Code Clone

#28 Refactored PreferencesUtilsTest.java to remove a software clone
  src/androidTest/java/de/dennisguse/opentracks/settings/PreferencesUtilsTest.java
Labels: Group #5, Technical Debt, Code Clone

#29 Removed Code Duplication from ContentPoviderUtils.java file
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/androidTest/java/de/dennisguse/opentracks/EspressoUITest.java
  src/androidTest/java/de/dennisguse/opentracks/settings/PreferencesUtilsTest.java
  src/main/java/de/dennisguse/opentracks/data/ContentProviderUtils.java
  src/main/java/de/dennisguse/opentracks/io/file/TrackFileFormat.java
  src/main/java/de/dennisguse/opentracks/services/MissingPermissionException.java
Labels: Code Clone

#34 Refactored duplicate trackpoints
  src/androidTest/java/de/dennisguse/opentracks/stats/TrackStatisticsUpdaterTest.java
Labels: Group #5, Code Clone

#35 Revert back the duplicate issue
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/AggregatedStatisticsAdapter.java
Labels: Group #5, Code Clone
